use_frameworks!

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'OCCustomKit_Example' do
  pod 'OCCustomKit', :path => '../'

  target 'OCCustomKit_Tests' do
    inherit! :search_paths

    
  end
end
